# Token
discord.token=${TOKEN}

# PaperTrail API URL
api.url=${API_URL}

# Shard Config
min.shard.id=${MIN_SHARD_ID:0}
max.shard.id=${MAX_SHARD_ID:0}
total.shards=${TOTAL_SHARDS:1}

# Twilight HTTP Proxy URL
# default value is a whitespace
twilight.http.proxy.url=${TWILIGHT_HTTP_PROXY_URL: }

#Port
quarkus.http.port=${PORT:8080}

# Logging Level
quarkus.log.level=${LOG_LEVEL:INFO}
# Log Categories
quarkus.log.category."io.github.eggy03.papertrail".level=DEBUG

# Analytics
quarkus.analytics.disabled=true

# Banner
quarkus.banner.path=banner.txt
# Native Build Args
quarkus.native.additional-build-args=\
    --trace-object-instantiation=java.security.SecureRandom,\
    --initialize-at-run-time=\
        com.neovisionaries.ws.client\\,\
        net.dv8tion.jda.internal.audio.CryptoAdapter$AbstractAaedAdapter\\,\
        net.dv8tion.jda.internal.requests.restaction.MessageCreateActionImpl