# Token
discord.token=${TOKEN}
# PaperTrail API URL
api.url=${API_URL}
# Shard Config
min.shard.id=${MIN_SHARD_ID:0}
max.shard.id=${MAX_SHARD_ID:0}
total.shards=${TOTAL_SHARDS:1}
# Twilight HTTP Proxy URL
# default value is a whitespace
twilight.http.proxy.url=${TWILIGHT_HTTP_PROXY_URL: }
# Logging Level
quarkus.log.level=INFO
# Analytics
quarkus.analytics.disabled=true
# Banner
quarkus.banner.path=banner.txt